sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 120402
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: wx59a383e26b947bca
    secret: 1bbe3aa238a86fd566aa114ce3e1f99e